"""Update Product model for OLX-style marketplace

Revision ID: 3829bd5d787d
Revises: 0dd801543306
Create Date: 2025-08-29 20:14:36.587640+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3829bd5d787d'
down_revision: Union[str, Sequence[str], None] = '0dd801543306'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_farmers_id'), 'farmers', ['id'], unique=False)
    op.alter_column('products', 'quantity',
               existing_type=sa.VARCHAR(length=50),
               server_default=None,
               existing_nullable=False)
    op.alter_column('products', 'category',
               existing_type=sa.VARCHAR(length=50),
               server_default=None,
               existing_nullable=False)
    op.alter_column('products', 'condition',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               existing_nullable=False)
    op.alter_column('products', 'status',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               existing_nullable=False)
    op.alter_column('products', 'location',
               existing_type=sa.VARCHAR(length=100),
               server_default=None,
               existing_nullable=False)
    op.alter_column('products', 'is_negotiable',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               nullable=True)
    op.alter_column('products', 'is_featured',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               nullable=True)
    op.alter_column('products', 'views',
               existing_type=sa.INTEGER(),
               server_default=None,
               nullable=True)
    op.create_index(op.f('ix_products_id'), 'products', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_products_id'), table_name='products')
    op.alter_column('products', 'views',
               existing_type=sa.INTEGER(),
               server_default=sa.text("'0'"),
               nullable=False)
    op.alter_column('products', 'is_featured',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text("'0'"),
               nullable=False)
    op.alter_column('products', 'is_negotiable',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text("'0'"),
               nullable=False)
    op.alter_column('products', 'location',
               existing_type=sa.VARCHAR(length=100),
               server_default=sa.text("'Not specified'"),
               existing_nullable=False)
    op.alter_column('products', 'status',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'available'"),
               existing_nullable=False)
    op.alter_column('products', 'condition',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'new'"),
               existing_nullable=False)
    op.alter_column('products', 'category',
               existing_type=sa.VARCHAR(length=50),
               server_default=sa.text("'Other'"),
               existing_nullable=False)
    op.alter_column('products', 'quantity',
               existing_type=sa.VARCHAR(length=50),
               server_default=sa.text("'1'"),
               existing_nullable=False)
    op.drop_index(op.f('ix_farmers_id'), table_name='farmers')
    # ### end Alembic commands ###
