"""Update TransactionItem model

Revision ID: e2ce2f824c28
Revises: c5134a038d3d
Create Date: 2025-08-29 19:42:24.040911+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e2ce2f824c28'
down_revision: Union[str, Sequence[str], None] = 'c5134a038d3d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transaction_items', sa.Column('price_per_unit', sa.Numeric(precision=10, scale=2), nullable=False))
    op.drop_column('transaction_items', 'unit_price')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transaction_items', sa.Column('unit_price', sa.NUMERIC(precision=10, scale=2), nullable=False))
    op.drop_column('transaction_items', 'price_per_unit')
    # ### end Alembic commands ###
